### ISSUE TITLE
Where can I find the Company::filterByRequest method

### ISSUE THREAD

**Issue by mauphung** [LaravelDaily/QuickAdminPanel-Classifieds-Directory#1]
Please tell me where can I find the Company::filterByRequest method called by method table of class HomePageController?
    public function table(Request $request)
    {
        $companies = Company::filterByRequest($request)->paginate(9);
        return view('mainTable.search', compact('companies'));
    }

**Comment by PovilasKorop** [comment]
@mauphung it's in `Company` model as a Scope: https://github.com/LaravelDaily/QuickAdminPanel-Classifieds-Directory/blob/cc069c00c5aa6611f595a6baebd006786faa1aac/app/Company.php#L65

Read more about Model Scopes here: https://laravel.com/docs/master/eloquent#query-scopes
