### ISSUE TITLE
Logo Uploads are linked to localhost

### ISSUE THREAD

**Issue by tahseenjamal** [LaravelDaily/QuickAdminPanel-Classifieds-Directory#6]
If you upload the image and then see the link associated with it in the HTML, it is localhost/storage/imagename

As localhost cannot be resolved, image doesn't show up

**Comment by PovilasKorop** [comment]
@tahseenjamal https://quickadminpanel.com/blog/why-its-important-to-change-app_url-in-laravel-env-file/

**Comment by tahseenjamal** [comment]
@PovilasKorop Thanks it resolved every where except for when I click the Category and there the url is 

http://my.doman.com/categories/1

Now at this point the image is not showing. And this is the only point
By the way apart from changing the URL, I also added symbolic link of storage inside public folder as public folder is

**Comment by tahseenjamal** [comment]
@PovilasKorop 
All pages image is showing except for http://my.domain.com/categories/1
at this point it is not showing

by the way I had to also create symbolic link of storage in public folder even after correct the localhost replace with FQDN

**Comment by PovilasKorop** [comment]
@tahseenjamal can you right-click on that image and see what is the full URL of that image? Sorry I can't debug it on your server.

**Comment by tahseenjamal** [comment]
I did a view source to check that in the html and here is the part of image, which I fetched and pasted below

<a href="http://php.tahseenjamal.com/companies/6"><img class="card-img-top img-fluid" src="http://php.tahseenjamal.com/thumb/{&quot;id&quot;:7,&quot;model_type&quot;:&quot;App\\Company&quot;,&quot;model_id&quot;:6,&quot;uuid&quot;:&quot;6f05a6d2-9736-4f71-ae2a-e09a4974a77a&quot;,&quot;collection_name&quot;:&quot;logo&quot;,&quot;name&quot;:&quot;5f7cc5a540c84_a&quot;,&quot;file_name&quot;:&quot;5f7cc5a540c84_a.jpg&quot;,&quot;mime_type&quot;:&quot;image\/jpeg&quot;,&quot;disk&quot;:&quot;public&quot;,&quot;conversions_disk&quot;:&quot;public&quot;,&quot;size&quot;:6800,&quot;manipulations&quot;:[],&quot;custom_properties&quot;:{&quot;generated_conversions&quot;:{&quot;thumb&quot;:true}},&quot;responsive_images&quot;:[],&quot;order_column&quot;:7,&quot;created_at&quot;:&quot;2020-10-06T19:29:43.000000Z&quot;,&quot;updated_at&quot;:&quot;2020-10-06T19:29:43.000000Z&quot;,&quot;url&quot;:&quot;http:\/\/php.tahseenjamal.com\/storage\/7\/5f7cc5a540c84_a.jpg&quot;,&quot;thumbnail&quot;:&quot;http:\/\/php.tahseenjamal.com\/storage\/7\/conversions\/5f7cc5a540c84_a-thumb.jpg&quot;}"/></a> `

**Comment by PovilasKorop** [comment]
@tahseenjamal oh right, it's trying to show the whole JSON of the object instead of a URL. Then you just need to edit `show.blade.php` file to show the correct data. Sorry we don't have time to fix it at the moment, please fix and make a pull request if you have time.

**Comment by tahseenjamal** [comment]
@PovilasKorop thanks for pointing to the correct file. I resolved the it. It was a very small change, let me know if you want me to share it

**Comment by tahseenjamal** [comment]
Sharing git difference after I made the change that resolved the issue

`
diff --git a/resources/views/mainTable/category.blade.php b/resources/views/mainTable/category.blade.php
index 896c358..8626a5c 100644
--- a/resources/views/mainTable/category.blade.php
+++ b/resources/views/mainTable/category.blade.php
@@ -98,7 +98,7 @@
                                 <div class="product-item bg-light">
                                     <div class="card">
                                         <div class="thumb-content">
-                                        @if($singleCompany->logo)<a href="{{ route('company', [$singleCompany->id]) }}"><img class="card-img-top img-fluid" src="{{ asset(env('UPLOAD_PATH').'/thumb/' . $singleCompany->logo) }}"/></a>@endif
+                                        @if($singleCompany->logo)<a href="{{ route('company', [$singleCompany->id]) }}"><img class="card-img-top img-fluid" src="{{ $singleCompany->logo->getUrl()) }}"/></a>@endif
                                         </div>
                                         <div class="card-body">
                                             <h4 class="card-title"><a href="{{ route('company', [$singleCompany->id]) }}">{{$singleCompany->name}}</a></h4>
@@ -125,4 +125,4 @@
 </section>
 
 
-@stop
`

**Comment by PovilasKorop** [comment]
@tahseenjamal thanks for sharing.
